name: 'Publish Tauri Android'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-android:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: setup android sdk
        uses: android-actions/setup-android@v3

      - name: set NDK environment
        run: |
          echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk/27.0.12077973" >> $GITHUB_ENV

      - name: install NPM dependencies
        run: npm install

      - name: Init Android
        run: npm run tauri android init

      - name: build tauri android
        run: npm run tauri android build -- --apk
      
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: wmax-android-apk
          path: src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk

      - name: Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
